services:
  prometheus:
    image: prom/prometheus
    container_name: web3_calculadora-prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
    command: "--config.file=/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - mongo-network
    pull_policy: always

networks:
  mongo-network:
    external: true
    name: web3_calculadora_mongo-network
