name: Release Images (tag v*.*.*)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component: [backend, frontend]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LOWER}-${{ matrix.component }}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build
        run: docker build -t "$IMAGE:$TAG" "${{ matrix.component }}"

      - name: Push
        run: docker push "$IMAGE:$TAG"
